@startuml

interface "IUserInterface" as UI{}

package Client{
class "Project42" as client
}

interface "ICardCollectionService" as CCS{}
interface "IUserService" as US{
+getUserID(id: String) : User
+register(user: User, password: String) : void
+updateUser(token: String, username? : String, password? : String) : void
+Login(username : String, password : String) : token
+getCards(userID : int) : List<Card>
+getDecks(userID : int) : List<Deck>
+saveCards(userID : int, Cards : List<Card>) : void
+saveDecks(userID : int, Decks : List<Deck>) : void
}
interface "IAnalyzeService" as AS{}
interface "IAiService" as AiS{}
interface "IMatchmakerService" as MS{}
interface "IBattleEngineService" as BES{}

client --> CCS
client --> US
client --> AS
client --> AiS
client --> MS
client --> BES
UI <-- client


@enduml