@startuml UserService

package "User Service" {
    class UserService {
        +getUserByUsername(username: String): ServiceResponse<User>
        +register(username: String, password: String, passwordConfirm: String): ServiceResponse<User>
        +updateUser(token: String, username?: String, password?: String, passwordConfirm?: String): ServiceResponse<User>
        +login(username: String, password: String): ServiceResponse<User>
        +getCards(token: String): ServiceResponse<List<Card>>
        +getDecks(token: String): ServiceResponse<List<Deck>>
        +saveCards(token: String, cards: List<Card>): ServiceResponse<List<Card>>
        +saveDecks(token: String, deckName: String, cardsInDeck: List<Card>): ServiceResponse<List<Deck>>
    }

    class User {
        -id: int
        -username: String
        -token: String
        -cards: List<Card>
        -decks: List<Deck>
        -wins: int
        -losses: int
        -mmr: int
        +User(id: int, username: string, wins: int, loss:int, cards:List<Card>?, decks:List<Deck>?, mmr: int)
        +User(username: string, token: string)
        +User(username: string)
        +addWin(): void
        +addLoss(): void
        +updateMmr(mmr: int): void
    }

    class Card {
        -id: int
        -name: String
        -healthPoints: int
        -power: int
        -cost: int
        -CardTribe: Tribe
        -CardRarity: Rarity
        +Card(id: int, name: String, power: int, healthPoints: int, cost: int, tribe: Tribe, rarity: Rarity)
        +Card(name: String, power: int, healthPoints: int, cost: int, tribe: Tribe, rarity: Rarity)
        +heal(amount: int): int
        +takeDamage(amount: int): int
        +buffPower(amount: int): int
        +debuffPower(amount: int): int
        +increaseCost(amount: int): int
        +decreaseCost(amount: int): int
    }

    class Deck {
        -id: int
        -name: String
        -cards: List<Card>
        +Deck(id: int, name: String, cards: List<Card>?)
        +Deck(name: String, cards: List<Card>?)
    }

    UserService --> Card
    UserService --> User
    UserService --> Deck
}

@enduml
