@startuml UserService

package "User Service" {
    class UserService {
        +getUser(id: String, password: String): User
        +register(user: User, password: String): void
        +updateUser(token: String, username?: String, password?: String): void
        +login(username: String, password: String): token
        +getCards(token: String): List<Card>
        +getDecks(token: String): List<Deck>
        +saveCards(token: String, cards: List<Card>): void
        +saveDecks(token: String, decks: List<Deck>): void
    }

    class User {
        -id: int
        -username: String
        -token: String
        -cards: List<Card>
        -decks: List<Deck>
        -wins: int
        -losses: int
        -mmr: int
        +getId(): String
        +getUsername(): String
        +setUsername(username: String): void
        +getToken(): String
        +getWins(): int
        -setWins(): void
        +addWin(): void
        +getLoss(): int
        -setLoss(): void
        +addLoss(): void
        +getCards(): List<Card>
        -setCards(cards: List<Card>): void
        +getDecks(): List<Deck>
        -setDecks(decks: List<Deck>): void
        +getMmr(): int
        -setMmr(): void
        +updateMmr(mmr: int): void
    }

    class Card {
        -id: int
        -name: String
        -healthPoints: int
        -power : int
        -cost : int
        -type: String
        -rarity: String
        +getId(): String
        +getName(): String
        +getHealthPoints(): int
        -setHealthPoints(): void
        +getPower(): int
        -setPower(): void
        +getCost(): int
        -setCost(): void
        +getType(): String
        +getRarity(): String
        +heal(amount: int): int
        +takeDamage(amount: int): int
        +buffPower(amount: int): int
        +debuffPower(amount: int): int
        +increaseCost(amount: int): int
        +decreaseCost(amount: int): int
    }

    class Deck {
        -id: int
        -name: String
        -cards: List<Card>
        +getId(): String
        +getName(): String
        +setName(name: String): String
        +getCards(): List<Card>
        +setCards(cards: List<Card>): List<Card>
    }

    UserService --> Card
    UserService --> User 
    UserService --> Deck
}

@enduml
